### ISSUE TITLE
Fails silently if app ID is invalid ~~Doesn't work on aarch64~~

### ISSUE THREAD

**Issue by ReactorScram** [tauri-apps/winrt-notification#17]
Hi just letting you know it doesn't work in my Windows aarch64 VM https://github.com/firezone/firezone/issues/4035

- Windows 11 Pro (free trial)
- Parallels Desktop 19 for Mac
- macOS Sonoma 14.3.1
- Apple M2 Pro

https://github.com/firezone/firezone/blob/535a61e2a130a8124dfc528766c5ba3ce6a6a12d/rust/gui-client/src-tauri/src/client/gui/os_windows.rs#L9

I built the same commit on Windows 11 for native x86_64 and it does work fine there. I put a tracing statement to be sure that code is called on the aarch64 build too.

**Comment by amrbashir** [comment]
could you please provide a minimal repro? @FabianLars tested the example in this repo on his machine and it worked fine.

**Comment by FabianLars** [comment]
Alrighty, so from further testing my assumption is that you installed the .msi on your x86_64 system in the past but not on the aarch64 system, could that be?
The .msi is responsible for registering your application ID and since the code you linked doesn't fall back to powershell like tauri does or the documention, it will try to use a non existant app ID which seems to prevent the notification from showing up at all.

**Comment by ReactorScram** [comment]
@FabianLars Yep that was it, oops. No relation to aarch64 at all.

And I see the underlying Windows API doesn't return any error at all, just silently fails if the app ID is not valid.

Is there a check I can put in my code to show an error next time I do this? like a `windows::IsThisAppIdInstalled` function? If you don't have one handy I'll research.

**Comment by FabianLars** [comment]
Nope, we don't have a check for that. I'd appreciate it though if you could post whatever you end up using :)

**Comment by ReactorScram** [comment]
The deciding factor seems to be whether `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Firezone\Firezone.lnk` exists. tl;dr: When I get around to it, I'll simply branch on whether that file exists or not. 

Since the company and app are both called "Firezone", I am not sure exactly which Tauri parameters this corresponds to. I'll get the `C:\ProgramData` bit from `known_folders` or some crate that automatically handles drives other than C and future compat.

According to the Windows docs https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager.createtoastnotifier?view=winrt-22621#windows-ui-notifications-toastnotificationmanager-createtoastnotifier(system-string)

- For a desktop app to display a toast, the app must have a shortcut on the Start screen.
- The shortcut must have an [AppUserModelID](https://learn.microsoft.com/en-us/windows/desktop/shell/appids).

I do see our app ID "dev.firezone.client" in the binary of the shortcut file. A precise solution might check for that file and parse it, and that file could theoretically be anywhere in the Start Menu dir. But since this is just for development, I'll just check the one path the file should be at, and if it exists, assume it's correct, because only the MSI could have installed it.

I guess I could use that to automatically fall back on Powershell and tell users, you can have the bare exe if you want, but it's gonna act weird for reasons beyond our control.
